language: go
go:
  - 1.9
script:
  - go test -v ./...
  - go build
  - sha256sum monit_exporter > monit_exporter.sha256
deploy:
  provider: releases
  api_key:
    secure: gPe5r5h+pt1ylQNjdlSr8AVZ83xU6hP+jtwb57+Nqpxb/Yf2DVomCjB43M71Sop6w6wvgsSERjYlYso2h9hiy/9vyya356FtW6qfJPshhSMpn/t3HNkKS828TVpuUqM+/T4K7Cs96zhlSrmN7UOcUNU0g9I39XLddQMb0/zVVKHeysmcgN+GzlvYpEoTM2n2TwqAg3C8egDuroDfqm3CJ4dtg7NO7YDVov1N1ZyhNopB0tOzA4ui5HSbJANPM/FO5b5b8qSjF+Iwdm/7B3IiE4meVgLIj8rf78zY78CcSpQTLnhKA0pqEMhRtOL8Iry58mesQ9jDWCVwBMABBfzLjuZKBapJSE4hhT6PZo5ZGUT+Yq+DXVlOSr9vivOSBQSkUjPB3KqB1l+qyErSs9slUdZJDgcPuajknigK/o5QIW2Nm8Wk3aOgzZUr4Da9g+JUVw5i9QPjqf8ArSGK82hYI6bCHBuHgDj0Rj20VbIIhlKxaDUUo5EJuFMCwiE2MegpR1HcMZNYKXqQCSDqnWxlpYwEwIEWA1s+wa7yW5AyLRyMPUsLVbawybqOXc1QehMp3XSSfb2lRgxetPcsYJAHqVqExSbpQc3smZfnuxJSgBaEaesVYT7qtl6g93QVwoFVLpLgBIJAHhN4oM422qGFmLL9hAoF/FxzGjo27V8WKzY= 
  file:
    - monit_exporter
    - monit_exporter.sha256
  skip_cleanup: true
  on:
    public_repo: melifaro/monit_exporter
    tags: true
